### ISSUE TITLE
A list of breaking changes we're holding back for 6.0

### ISSUE THREAD

**Issue by yob** [buildkite/elastic-ci-stack-for-aws#792]
We have a few breaking changes we might make in 6.0, whenever that ends up being. I considered making a GitHub milestone for this list, but we don't have a culture of using them and I worried we might overlook it.

* [x] update awscli to v2 #688
* [ ] remove the `IMDSv2Tokens` param added in #789 and just make v2 tokens required all the t ime
* [x] remove deprecated `SpotPrice` param #710
* [ ] Enable SSM access and disable SSH access #738 
* [x] Rename SecurityGroupId to SecurityGroupIds?
* [x] Make instance names default to the stack name
* [x] Rename base branch from master to main - this would cause people using master branch releases to stop receiving builds

See also: [Agent: A list of breaking changes we're holding back for 4.0](https://github.com/buildkite/agent/issues/1391)

**Comment by nitrocode** [comment]
Renaming `SecurityGroupId` to `SecurityGroupIds` would be good too

**Comment by woodhull** [comment]
Update docker to 20.x?

**Comment by chloeruka** [comment]
> Update docker to 20.x?

@woodhull Docker bumps are not usually considered breaking, are there significant implications of moving to v20?

@yob I'd also like to see #738 if we don't merge it sooner.

**Comment by yob** [comment]
Thanks all - list updated

**Comment by jdub** [comment]
If you're doing `SecurityGroupIds`, perhaps `ManagedPolicyARNs`? Just discovered it. 😆

**Comment by nitrocode** [comment]
@chloeruka that wouldn't be a breaking change since ssh access would still be available just through ssm instead of port 22.

If it's not a breaking change, could it be added prior to a 6.0 release?

**Comment by chloeruka** [comment]
It's not so much the availability of equivalent/replacement features, but removal of parameters that would make us consider it more appropriate for a major version. Changing things around might require users adjust parameters or automation surrounding their stacks. We want low friction Cloudformation upgrades since it's currently tied to Agent updates.

**Comment by nitrocode** [comment]
I'd like to second the docker `20.x` upgrade as that would allow us to no longer have to set environment variables `DOCKER_EXPERIMENTAL` and `DOCKER_CLI_EXPERIMENTAL` which would deprecate the `EnableDockerExperimental` parameter on the stack.

**Comment by triarius** [comment]
v6 is out, so I'm going to close this.
